spring.datasource.url=jdbc:sqlite:mi-base-de-datos.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# ================= CORREO GMAIL =================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=keviningeniero123@gmail.com
spring.mail.password=gzkj azbi rjbw gpow
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true